---
# file: roles/base/tasks/logwatch.yaml
# Sets up logwatch to monitor server and send emails
- name: install logwatch
  apt: name=logwatch state=latest
  tags: apt, logwatch

- name: Set up Postfix to relay mail
  debconf: name=postfix
            question='{{ item.question }}'
            value='{{ item.value }}'
            vtype='{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }
  tags: logwatch

- name: Email log summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
              state=present create=yes
  tags: logwatch
