# file: library/ssh_setup.yaml
# Helper function to allow auto-discovery of ssh settings for a host.
# Particularly useful for deployments where you are changing the ssh port as
# part of an initial setup and install.

- set_fact:
    ssh_details_known: false

#### Executed when we have a private key defined ####
- include: library/ssh_setup/ssh_setup_private_key.yaml # TODO: replace `include` with `include_tasks` due to deprecation
  when: (ansible_ssh_private_key_file is defined) and (ssh_details_known is false)

#### Executed when no private key defined / cant connect with key ####
 library/ssh_setup/ssh_setup_basic.yaml
  when: ssh_details_known is false

# If the SSH port is neither the default or the configured, give up.
- name: Fail if we cant connect
  fail:
    msg: "Unable to connect via SSH."
  when: ssh_details_known is false

# - debug:
#     msg: "User: {{ ansible_user }} | Port: {{ ansible_port }} | Key: {{ ansible_ssh_private_key_file|default(none) }}"
    #   - "Pass: {{ ansible_become_pass|default(none) }}"
    #   - "Key: {{ ansible_ssh_private_key_file|default(none) }}"
    #   - "Port: {{ ansible_port }}"
    #   - "Target: {{ ansible_fqdn }}"
