---
# file: base.yaml
# Playbook to deploy the `base` role onto a server
- hosts: all
  gather_facts: true
  become: true
  vars_prompt:
    - name: "logwatch_email"
      prompt: "Enter email address for logwatch email delivery"
      private: "no"
    - name: "deploy_user_name"
      prompt: "Name of admin user"
      private: "no"
      default: "adminlocal"
    - name: "deploy_user_ssh_public_key"
      prompt: "Path to existing PUBLIC ssh key"
      private: "no"
      default: "~/.ssh/id_rsa.pub"
    - name: "deploy_user_ssh_pivate_key"
      prompt: "Path to existing PRIVATE ssh key"
      private: "no"
      default: "~/.ssh/id_rsa"
    - name: "regenerate_moduli"
      prompt: "Regenerate Moduli (recommended but slow) [yes/no]"
      private: "no"
      default: "no"
    - name: "enable_avahi"
      prompt: "Enable avahi mDNS service discovery [yes/no]"
      private: "no"
      default: "yes"
  roles:
    - base
