---
# file: roles/base/vars/main.yml

# only these users will have SSH access to the server
ssh_users:
    - name: "{{ ubuntu_common_deploy_user_name }}"

# can add additional users here if needed
users:
  - "{{ ssh_users }}"

enable_avahi: true